---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Naming/FileName:
  Exclude:
    - lib/rails-env.rb

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
