sudo: false
cache: bundler
rvm:
  - 2.7.1
  - 2.6.5
script: bundle exec rake
gemfile:
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_5_0.gemfile
env:
  global:
    secure: irnD3t0HmZ2dG0GVHhVtzgitUX7m4GtJ3uK55vGp7JWPHHIL4daQORfHcuu3uJW0OaECf4WQUODy0HM2dArXZ1DrOjm7cnfr03oZKKi7Ft5ECOcQUagvsir7zJ+icBJ8WzcIl7V0p3aHNXEQ9jNIX1/v+Edcs+HXEdlFpp0Vt7Y=
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
before_install:
  - gem install bundler
before_script:
  - "curl -L
    https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter"
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
notifications:
  email: false
